osx_image: xcode11 # define OS X image which will be mounted

dist: trusty # use Ubuntu Trusty for Linux operation system

# Note: if you switch to sudo: false, you'll need to launch chrome with --no-sandbox.
# See https://github.com/travis-ci/travis-ci/issues/8836
sudo: required

# Define Node.js as the programming language as we have a web application
language: node_js
node_js: 'v12.6.0'

addons:
  chrome: stable # Install chrome stable on operating systems
  apt:
  packages:
    - xvfb # Required for spectrong tests 

# A list of operating systems which are used for tests
os:
  - linux
  - osx

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  yarn: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

before_cache:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm -rf $HOME/.cache/electron-builder/wine; fi

# These commands are executed before the scripts are executed
install:
  # On OS X we first need to install Yarn via Homebrew
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install yarn; fi
  # Install all dependencies listed in your package.json file
  # - yarn

  # Install for spectron
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

script:

  - echo "Build linux version"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn build linux; fi

  - echo "Build OS X version"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn build mac; fi

  - echo "Run e2e testing"
  - yarn test:e2e

  # - echo "Deploy linux version to GitHub"
  # - if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn release:linux; fi

  # - echo "Deploy windows version to GitHub"
  # - if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn release:win; fi

  # - echo "Deploy mac version to GitHub"
  # - if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn release:mac; fi